# Generated by Django 3.1.7 on 2021-05-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='ame',
            new_name='name',
        ),
    ]
