# Generated by Django 3.1.7 on 2021-05-24 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210524_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_number', models.IntegerField(default=0)),
                ('unit_measure', models.CharField(choices=[('mL', 'mL'), ('Unit', 'Unit')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='productinput',
            name='batch',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='productinput',
            name='date_expiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productinput',
            name='date_production',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.dosageform'),
        ),
    ]
