# Generated by Django 3.1.7 on 2021-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210524_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageform',
            name='unit_measure',
            field=models.CharField(choices=[('mL', 'mL'), ('cap', 'Capsula'), ('tab', 'Tableta'), ('grag', 'Gragea'), ('comp', 'Comprimido'), ('sob', 'Sobre'), ('amp-iny', 'Ampolla inyectable'), ('amp-beb', 'Ampolla bebible'), ('fras', 'Frasco'), ('bot', 'Botella'), ('ovuls', 'Ovulo'), ('sups', 'Supositorio')], max_length=200),
        ),
    ]
