# Generated by Django 3.1.7 on 2021-05-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210524_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
    ]
