# Generated by Django 3.1.7 on 2021-05-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210524_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='address2',
            new_name='email',
        ),
    ]
