# Generated by Django 3.1.7 on 2021-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210524_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
