# Generated by Django 3.1.7 on 2021-06-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_laboratory_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinput',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
